name: Diagnose Metadata and Clear Calendar

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          
      - name: Install dependencies
        run: pip install requests beautifulsoup4 google-auth-oauthlib google-auth-httplib2 google-api-python-client python-dateutil
        
      - name: Run metadata diagnosis and clear calendar
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
        run: python calendar/diagnose_metadata.py
        
      - name: Verify diagnosis file exists
        run: |
          ls -la metadata_diagnosis.json || echo "File not found"
          cat metadata_diagnosis.json || echo "Unable to read file"
          
      - name: Upload diagnosis results
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: metadata-diagnosis
          path: metadata_diagnosis.json