name: Update Google Calendar

on:
  # push:
  #   branches: [main]
  # schedule:
  #   - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:  # Manual trigger

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          
      - name: Install dependencies
        run: pip install google-auth-oauthlib google-auth-httplib2 google-api-python-client python-dateutil
        
      - name: Run calendar updater
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }} # Add this secret if not already set
        run: python calendar/update_calendar.py
        
      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GHCR_TOKEN }}
          script: |
            const { execSync } = require('child_process');
            execSync('git config --local user.name "github-actions[bot]"');
            execSync('git config --local user.email "github-actions[bot]@users.noreply.github.com"');
            execSync('git add data/light_novel_releases.json');
            try {
              execSync('git commit -m "Update calendar added dates"');
              execSync('git push');
            } catch (error) {
              console.log("No changes to commit");
            }